
spring.data.mongodb.uri=mongodb+srv://rupeshhcs_db_user:SN3LHXVzjASctMU2@cluster0.g978z5c.mongodb.net/myjournaluser?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.databse=myjournaluser
#spring.data.mongodb.username=username
#spring.data.mongodb.password=password
#spring.data.mongodb.auto-index-creation=true
server.port=8090